server:
  port: 9000

spring:
  application:
    name: cards
  # as default behavior activate this profile
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8071/