server:
  port: 8090

spring:
  application:
    name: loans
  # as default behavior activate this profile
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8071/