server:
  port: 9010

spring:
  application:
    name: "message"

  cloud:
    function:
      definition: email|sms # compose 2 functions into a single unit
    stream:
      bindings:
        emailsms-in-0: # in = input binding
          destination: send-communication # the name we also add in rabbitMQ, and we use as a reference
          group: ${spring.application.name}
        emailsms-out-0: # out = output binding
          destination: communication-sent
      # Kafka solution
      kafka:
        binder:
          brokers:
            - localhost:9092

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: guest
#    password: guest
#    connection-timeout: 20s